# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Run tests"
  lane :tests do
    
    # match(type: "development", readonly: true)
    scan(
      workspace: "BrasilianLeague.xcworkspace",
      scheme: "AllTests",
      device: 'iPhone 14 Pro Max (16.0)',
      code_coverage: true,
      build_for_testing: true
    )
  end

  desc "Build and send to testflight"
  lane :release do
    match(type: "appstore", readonly: true)
    build_app(workspace: "BrasilianLeague.xcworkspace")
  end

end