on:
  push:
    branches:
      - 'main'
    pull_request:
      types: [opened, reopened]

name: Run tests
jobs:
  tests:
    name: Build
    runs-on: macOS-12
    strategy:
      matrix:
        destination:
          - 'platform=iOS Simulator,OS=16.0,name=iPhone 14 Pro Max'
    steps:
      - name: Checkout
        uses: actions/checkout@master
      
      - name: Install tools
        run: |
          brew install swiftgen
          bundle install
      
      - name: Build and Test
        run: bundle exec fastlane ios tests
        env:
          destination: '${{ matrix.destination }}'